//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HugeJSONViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HugeJSONViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting into display data.
        /// </summary>
        internal static string ConvertingJsonCaption {
            get {
                return ResourceManager.GetString("ConvertingJsonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string ConvertingJsonWaitMessage {
            get {
                return ResourceManager.GetString("ConvertingJsonWaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying.
        /// </summary>
        internal static string DisplayingJsonCaption {
            get {
                return ResourceManager.GetString("DisplayingJsonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string DisplayingJsonWaitMessage {
            get {
                return ResourceManager.GetString("DisplayingJsonWaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error accessing file: {0}
        ///{1}.
        /// </summary>
        internal static string ErrorAccessingFile {
            get {
                return ResourceManager.GetString("ErrorAccessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading JSON.
        /// </summary>
        internal static string ErrorLoadingJson {
            get {
                return ResourceManager.GetString("ErrorLoadingJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing JSON: {0}
        ///{1}.
        /// </summary>
        internal static string ErrorParsingJson {
            get {
                return ResourceManager.GetString("ErrorParsingJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size ({0}) might not fit into the memory of your PC.
        ///If so, it will slow down things tremendously.
        ///Continue anyway?.
        /// </summary>
        internal static string FileTooLargeWarning {
            get {
                return ResourceManager.GetString("FileTooLargeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.000} GB.
        /// </summary>
        internal static string HumanReadableGB {
            get {
                return ResourceManager.GetString("HumanReadableGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.000} MB.
        /// </summary>
        internal static string HumanReadableKB {
            get {
                return ResourceManager.GetString("HumanReadableKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.000} kB.
        /// </summary>
        internal static string HumanReadableMB {
            get {
                return ResourceManager.GetString("HumanReadableMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1:00}.{2:000} min.
        /// </summary>
        internal static string HumanReadableTime {
            get {
                return ResourceManager.GetString("HumanReadableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name: {0}
        ///{1}.
        /// </summary>
        internal static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing JSON.
        /// </summary>
        internal static string ParsingJsonCaption {
            get {
                return ResourceManager.GetString("ParsingJsonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string ParsingJsonWaitMessage {
            get {
                return ResourceManager.GetString("ParsingJsonWaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance warning.
        /// </summary>
        internal static string PerformanceWarning {
            get {
                return ResourceManager.GetString("PerformanceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%.
        /// </summary>
        internal static string ProcessingJsonProgress {
            get {
                return ResourceManager.GetString("ProcessingJsonProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        internal static string StreamingProgress {
            get {
                return ResourceManager.GetString("StreamingProgress", resourceCulture);
            }
        }
    }
}
